# Nodeport directly exposes service use ingress instead

# apiVersion: v1
# kind: Service
# metadata:
#   name: prometheus
#   namespace: prometheus
# spec:
#   selector:
#     app: prometheus
#   type: NodePort
#   ports:
#   - name: prometheus
#     protocol: TCP
#     port: 9090 
#     nodePort: 30900